Handle a Turing machine becoming stuck
As with our DPDA simulation, we need to do a bit more work to
gracefully handle a Turing machine becoming stuck:

>> tape = Tape.new(['1', '2', '1'], '1', [], '_')
=> #<Tape 121(1)>
>> dtm = DTM.new(TMConfiguration.new(1, tape), [3], rulebook)
=> #<struct DTM …>
>> dtm.run
NoMethodError: undefined method `follow' for nil:NilClass

This time we don’t need a special representation of a stuck
state. Unlike a PDA, a Turing machine doesn’t have an external input,
so we can tell it’s stuck just by looking at its rulebook and current
configuration.

Now the simulation will notice it’s stuck and stop automatically:

$ irb --simple-prompt

>> require './tape.rb'
>> require './tm_rule.rb'
>> require './tm_configuration.rb'
>> require './dtm_rulebook.rb'
>> require './dtm.rb'

>> rulebook = DTMRulebook.new([
     TMRule.new(1, '0', 2, '1', :right),
     TMRule.new(1, '1', 1, '0', :left),
     TMRule.new(1, '_', 2, '1', :right),
     TMRule.new(2, '0', 2, '0', :right),
     TMRule.new(2, '1', 2, '1', :right),
     TMRule.new(2, '_', 3, '_', :left)
   ])
>> tape = Tape.new(['1', '2', '1'], '1', [], '_')

>> dtm = DTM.new(TMConfiguration.new(1, tape), [3], rulebook)
=> #<struct DTM …>
>> dtm.run
=> nil
>> dtm.current_configuration
=> #<struct TMConfiguration state=1, tape=#<Tape 1(2)00>>
>> dtm.accepting?
=> false
>> dtm.stuck?
=> true